### ISSUE TITLE
Missing gmax_meeting_sharecode

### ISSUE THREAD

**Issue by ncd76** [TotalPerformanceData/gmaxfeed#7]
gmax_meeting_sharecode is NULL in gmax_race

SELECT * FROM gmax_race WHERE gmax_meeting_sharecode IS NULL ORDER BY post_time asc LIMIT 100 ;

**Comment by gos-qs** [comment]
This happened because another process/service has added races into gmax_race without the additional fields or foreign records which didn't play nicely with the way my loop logic CRUDs them, possibly something from the pricing server reports? I've put a checker in place to "repair" these records and set them right if it happens again, the check occurs just before checks for new racelists so shouldn't happen again for UK/USA/Ca races. Until French races are in the racelist feed, they will remain orphaned as are currently.
